/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.uark.csce3513.team18.lasertag;

import java.sql.SQLException;
import javax.swing.JTextField;
import java.util.TimerTask;

/**
 *
 * @authors Steven, Cory
 */
public class Entry extends javax.swing.JFrame {

    int timeLeft = 6;
    /**
     * Creates new form TempFrame
     */
    public Entry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        blueTeam = new javax.swing.JLabel();
        redTeam = new javax.swing.JLabel();
        blueID1 = new javax.swing.JTextField();
        blueID2 = new javax.swing.JTextField();
        blueID3 = new javax.swing.JTextField();
        blueID4 = new javax.swing.JTextField();
        blueID5 = new javax.swing.JTextField();
        blueID6 = new javax.swing.JTextField();
        blueID7 = new javax.swing.JTextField();
        blueID8 = new javax.swing.JTextField();
        blueID9 = new javax.swing.JTextField();
        blueID10 = new javax.swing.JTextField();
        blueID11 = new javax.swing.JTextField();
        blueID12 = new javax.swing.JTextField();
        blueID13 = new javax.swing.JTextField();
        blueID14 = new javax.swing.JTextField();
        blueID15 = new javax.swing.JTextField();
        redID1 = new javax.swing.JTextField();
        redID2 = new javax.swing.JTextField();
        redID3 = new javax.swing.JTextField();
        redID4 = new javax.swing.JTextField();
        redID5 = new javax.swing.JTextField();
        redID6 = new javax.swing.JTextField();
        redID7 = new javax.swing.JTextField();
        redID8 = new javax.swing.JTextField();
        redID9 = new javax.swing.JTextField();
        redID10 = new javax.swing.JTextField();
        redID11 = new javax.swing.JTextField();
        redID12 = new javax.swing.JTextField();
        redID13 = new javax.swing.JTextField();
        redID14 = new javax.swing.JTextField();
        redID15 = new javax.swing.JTextField();
        blueNickname1 = new javax.swing.JTextField();
        blueNickname2 = new javax.swing.JTextField();
        blueNickname3 = new javax.swing.JTextField();
        blueNickname4 = new javax.swing.JTextField();
        blueNickname5 = new javax.swing.JTextField();
        blueNickname6 = new javax.swing.JTextField();
        blueNickname7 = new javax.swing.JTextField();
        blueNickname8 = new javax.swing.JTextField();
        blueNickname9 = new javax.swing.JTextField();
        blueNickname10 = new javax.swing.JTextField();
        blueNickname11 = new javax.swing.JTextField();
        blueNickname12 = new javax.swing.JTextField();
        blueNickname13 = new javax.swing.JTextField();
        blueNickname14 = new javax.swing.JTextField();
        blueNickname15 = new javax.swing.JTextField();
        redNickname1 = new javax.swing.JTextField();
        redNickname2 = new javax.swing.JTextField();
        redNickname3 = new javax.swing.JTextField();
        redNickname4 = new javax.swing.JTextField();
        redNickname5 = new javax.swing.JTextField();
        redNickname6 = new javax.swing.JTextField();
        redNickname7 = new javax.swing.JTextField();
        redNickname8 = new javax.swing.JTextField();
        redNickname9 = new javax.swing.JTextField();
        redNickname10 = new javax.swing.JTextField();
        redNickname11 = new javax.swing.JTextField();
        redNickname12 = new javax.swing.JTextField();
        redNickname13 = new javax.swing.JTextField();
        redNickname14 = new javax.swing.JTextField();
        redNickname15 = new javax.swing.JTextField();
        blueCount1 = new javax.swing.JLabel();
        blueCount2 = new javax.swing.JLabel();
        blueCount3 = new javax.swing.JLabel();
        blueCount4 = new javax.swing.JLabel();
        blueCount5 = new javax.swing.JLabel();
        blueCount6 = new javax.swing.JLabel();
        blueCount7 = new javax.swing.JLabel();
        blueCount8 = new javax.swing.JLabel();
        blueCount9 = new javax.swing.JLabel();
        blueCount10 = new javax.swing.JLabel();
        blueCount11 = new javax.swing.JLabel();
        blueCount12 = new javax.swing.JLabel();
        blueCount13 = new javax.swing.JLabel();
        blueCount14 = new javax.swing.JLabel();
        blueCount15 = new javax.swing.JLabel();
        redCount1 = new javax.swing.JLabel();
        redCount2 = new javax.swing.JLabel();
        redCount3 = new javax.swing.JLabel();
        redCount4 = new javax.swing.JLabel();
        redCount5 = new javax.swing.JLabel();
        redCount6 = new javax.swing.JLabel();
        redCount7 = new javax.swing.JLabel();
        redCount8 = new javax.swing.JLabel();
        redCount9 = new javax.swing.JLabel();
        redCount10 = new javax.swing.JLabel();
        redCount11 = new javax.swing.JLabel();
        redCount12 = new javax.swing.JLabel();
        redCount13 = new javax.swing.JLabel();
        redCount14 = new javax.swing.JLabel();
        redCount15 = new javax.swing.JLabel();
        editPlayers = new javax.swing.JToggleButton();
        bluePlayerIDLabel = new javax.swing.JLabel();
        redPlayerIDLabel = new javax.swing.JLabel();
        redPlayerCodenameLabel = new javax.swing.JLabel();
        bluePlayerCodenameLabel = new javax.swing.JLabel();
        startGame = new javax.swing.JButton();
        StartTimerLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        blueTeam.setText("BLUE TEAM");

        redTeam.setText("RED TEAM");

        blueID1.setEditable(false);
        blueID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueID1ActionPerformed(evt);
            }
        });

        blueID2.setEditable(false);
        blueID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueID2ActionPerformed(evt);
            }
        });

        blueID3.setEditable(false);

        blueID4.setEditable(false);

        blueID5.setEditable(false);

        blueID6.setEditable(false);

        blueID7.setEditable(false);

        blueID8.setEditable(false);

        blueID9.setEditable(false);

        blueID10.setEditable(false);

        blueID11.setEditable(false);

        blueID12.setEditable(false);

        blueID13.setEditable(false);

        blueID14.setEditable(false);

        blueID15.setEditable(false);
        blueID15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueID15ActionPerformed(evt);
            }
        });

        redID1.setEditable(false);

        redID2.setEditable(false);

        redID3.setEditable(false);

        redID4.setEditable(false);

        redID5.setEditable(false);

        redID6.setEditable(false);

        redID7.setEditable(false);

        redID8.setEditable(false);

        redID9.setEditable(false);

        redID10.setEditable(false);

        redID11.setEditable(false);

        redID12.setEditable(false);

        redID13.setEditable(false);

        redID14.setEditable(false);

        redID15.setEditable(false);

        blueNickname1.setEditable(false);

        blueNickname2.setEditable(false);

        blueNickname3.setEditable(false);

        blueNickname4.setEditable(false);

        blueNickname5.setEditable(false);

        blueNickname6.setEditable(false);

        blueNickname7.setEditable(false);

        blueNickname8.setEditable(false);

        blueNickname9.setEditable(false);

        blueNickname10.setEditable(false);

        blueNickname11.setEditable(false);

        blueNickname12.setEditable(false);

        blueNickname13.setEditable(false);

        blueNickname14.setEditable(false);

        blueNickname15.setEditable(false);

        redNickname1.setEditable(false);

        redNickname2.setEditable(false);

        redNickname3.setEditable(false);

        redNickname4.setEditable(false);

        redNickname5.setEditable(false);

        redNickname6.setEditable(false);

        redNickname7.setEditable(false);

        redNickname8.setEditable(false);

        redNickname9.setEditable(false);

        redNickname10.setEditable(false);

        redNickname11.setEditable(false);

        redNickname12.setEditable(false);

        redNickname13.setEditable(false);

        redNickname14.setEditable(false);

        redNickname15.setEditable(false);

        blueCount1.setText("01");

        blueCount2.setText("02");

        blueCount3.setText("03");

        blueCount4.setText("04");

        blueCount5.setText("05");

        blueCount6.setText("06");

        blueCount7.setText("07");

        blueCount8.setText("08");

        blueCount9.setText("09");

        blueCount10.setText("10");

        blueCount11.setText("11");

        blueCount12.setText("12");

        blueCount13.setText("13");

        blueCount14.setText("14");

        blueCount15.setText("15");

        redCount1.setText("01");

        redCount2.setText("02");

        redCount3.setText("03");

        redCount4.setText("04");

        redCount5.setText("05");

        redCount6.setText("06");

        redCount7.setText("07");

        redCount8.setText("08");

        redCount9.setText("09");

        redCount10.setText("10");

        redCount11.setText("11");

        redCount12.setText("12");

        redCount13.setText("13");

        redCount14.setText("14");

        redCount15.setText("15");

        editPlayers.setText("Edit Players (Off)");
        editPlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPlayersActionPerformed(evt);
            }
        });

        bluePlayerIDLabel.setText("ID");

        redPlayerIDLabel.setText("ID");

        redPlayerCodenameLabel.setText("Codename");

        bluePlayerCodenameLabel.setText("Codename");

        startGame.setText("Start Game!");
        startGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGameActionPerformed(evt);
            }
        });

        StartTimerLabel.setText("00:00");
        StartTimerLabel.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(blueCount15)
                    .addComponent(blueCount14)
                    .addComponent(blueCount13)
                    .addComponent(blueCount12)
                    .addComponent(blueCount11)
                    .addComponent(blueCount10)
                    .addComponent(blueCount9)
                    .addComponent(blueCount8)
                    .addComponent(blueCount7)
                    .addComponent(blueCount6)
                    .addComponent(blueCount5)
                    .addComponent(blueCount4)
                    .addComponent(blueCount3)
                    .addComponent(blueCount2)
                    .addComponent(blueCount1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(blueTeam)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(blueID15, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(blueNickname15, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(editPlayers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(blueID2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(blueID14, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(blueID13, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(blueID12, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(blueID11, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(blueID10, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(blueID9, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(blueID8, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(blueID7, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(blueID6, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(blueID5, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(blueID4, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(blueID3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(blueID1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(bluePlayerIDLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bluePlayerCodenameLabel)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(blueNickname13, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(blueNickname12, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(blueNickname11, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(blueNickname10, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(blueNickname9, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(blueNickname8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(blueNickname7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(blueNickname6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(blueNickname5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(blueNickname4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(blueNickname3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(blueNickname2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(blueNickname1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(blueNickname14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(redCount2)
                                .addComponent(redCount3)
                                .addComponent(redCount4)
                                .addComponent(redCount5)
                                .addComponent(redCount6)
                                .addComponent(redCount7)
                                .addComponent(redCount8)
                                .addComponent(redCount9)
                                .addComponent(redCount10)
                                .addComponent(redCount11)
                                .addComponent(redCount12)
                                .addComponent(redCount13, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(redCount1, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(redID2)
                                        .addComponent(redID3)
                                        .addComponent(redID4)
                                        .addComponent(redID5)
                                        .addComponent(redID6)
                                        .addComponent(redID7)
                                        .addComponent(redID8)
                                        .addComponent(redID9)
                                        .addComponent(redID10)
                                        .addComponent(redID11, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(redID12, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(redID13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(redNickname2)
                                        .addComponent(redNickname3)
                                        .addComponent(redNickname4)
                                        .addComponent(redNickname5)
                                        .addComponent(redNickname6)
                                        .addComponent(redNickname7)
                                        .addComponent(redNickname8)
                                        .addComponent(redNickname9)
                                        .addComponent(redNickname10)
                                        .addComponent(redNickname11)
                                        .addComponent(redNickname12)
                                        .addComponent(redNickname13)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(redID1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(redPlayerIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(redTeam))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(redNickname1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(redPlayerCodenameLabel)
                                        .addComponent(StartTimerLabel, javax.swing.GroupLayout.Alignment.TRAILING)))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(redCount15)
                                .addComponent(redCount14))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(redID14)
                                .addComponent(redID15, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(redNickname14)
                                .addComponent(redNickname15))))
                    .addComponent(startGame, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(blueTeam)
                            .addComponent(redTeam))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bluePlayerIDLabel)
                            .addComponent(bluePlayerCodenameLabel))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(blueID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blueCount1)
                            .addComponent(blueNickname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(blueID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blueNickname2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blueCount2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(blueNickname3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(blueNickname4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(blueNickname5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(blueNickname6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(blueNickname7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(blueNickname8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(blueNickname9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(blueNickname10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(blueNickname11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(blueNickname12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(blueNickname13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(blueNickname14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(blueID3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(blueCount3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(blueID4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(blueCount4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(blueID5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(blueCount5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(blueID6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(blueCount6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(blueID7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(blueCount7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(blueID8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(blueCount8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(blueID9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(blueCount9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(blueID10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(blueCount10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(blueID11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(blueCount11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(blueID12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(blueCount12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(blueID13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(blueCount13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(blueID14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(blueCount14))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(blueID15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blueNickname15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blueCount15)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(redPlayerIDLabel)
                                    .addComponent(redPlayerCodenameLabel)))
                            .addComponent(StartTimerLabel))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(redID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(redNickname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(redCount1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(redNickname2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(redNickname3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(redNickname4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(redNickname5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(redNickname6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(redNickname7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(redNickname8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(redNickname9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(redNickname10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(redNickname11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(redID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(redCount2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(redID3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(redCount3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(redID4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(redCount4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(redID5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(redCount5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(redID6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(redCount6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(redID7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(redCount7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(redID8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(redCount8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(redID9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(redCount9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(redID10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(redCount10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(redID11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(redCount11))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(redNickname12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(redNickname13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(redID12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(redCount12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(redID13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(redCount13))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(redNickname14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(redNickname15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(redID14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(redCount14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(redID15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(redCount15))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editPlayers)
                    .addComponent(startGame))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void blueID15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueID15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blueID15ActionPerformed

    private void blueID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blueID1ActionPerformed

    private void blueID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blueID2ActionPerformed


    private void submitPlayerEntry(JTextField id, JTextField codeName) {
        String idInfo = id.getText();
        if (idInfo.isEmpty()) {
            return;
        } else {
            int newId = Integer.parseInt(idInfo);
            String nickName = codeName.getText();
        
            Player playerSubmission = new Player(newId, nickName);
        
            String url = "jdbc:postgresql://db.xbbsojmzbwlxprdwscxj.supabase.co:5432/postgres";
            String username = "postgres";
            String password = "team18isthebest";
        
            Database database = new Database(url, username, password);
            
            try {
                database.connect();
                try {
                    if (database.getPlayer(newId).getId() == newId) {
                        database.updatePlayer(playerSubmission);
                    } 
                } catch (SQLException er) {
                    database.createPlayer(playerSubmission);
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }

    
    private void editPlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPlayersActionPerformed
        if(editPlayers.getText()=="Edit Players (Off)"){
            editPlayers.setText("Edit Players (On)");
            blueID1.setEditable(true);
            blueID2.setEditable(true);
            blueID3.setEditable(true);
            blueID4.setEditable(true);
            blueID5.setEditable(true);
            blueID6.setEditable(true);
            blueID7.setEditable(true);
            blueID8.setEditable(true);
            blueID9.setEditable(true);
            blueID10.setEditable(true);
            blueID11.setEditable(true);
            blueID12.setEditable(true);
            blueID13.setEditable(true);
            blueID14.setEditable(true);
            blueID15.setEditable(true);
            blueNickname1.setEditable(true);
            blueNickname2.setEditable(true);
            blueNickname3.setEditable(true);
            blueNickname4.setEditable(true);
            blueNickname5.setEditable(true);
            blueNickname6.setEditable(true);
            blueNickname7.setEditable(true);
            blueNickname8.setEditable(true);
            blueNickname9.setEditable(true);
            blueNickname10.setEditable(true);
            blueNickname11.setEditable(true);
            blueNickname12.setEditable(true);
            blueNickname13.setEditable(true);
            blueNickname14.setEditable(true);
            blueNickname15.setEditable(true);
            redID1.setEditable(true);
            redID2.setEditable(true);
            redID3.setEditable(true);
            redID4.setEditable(true);
            redID5.setEditable(true);
            redID6.setEditable(true);
            redID7.setEditable(true);
            redID8.setEditable(true);
            redID9.setEditable(true);
            redID10.setEditable(true);
            redID11.setEditable(true);
            redID12.setEditable(true);
            redID13.setEditable(true);
            redID14.setEditable(true);
            redID15.setEditable(true);
            redNickname1.setEditable(true);
            redNickname2.setEditable(true);
            redNickname3.setEditable(true);
            redNickname4.setEditable(true);
            redNickname5.setEditable(true);
            redNickname6.setEditable(true);
            redNickname7.setEditable(true);
            redNickname8.setEditable(true);
            redNickname9.setEditable(true);
            redNickname10.setEditable(true);
            redNickname11.setEditable(true);
            redNickname12.setEditable(true);
            redNickname13.setEditable(true);
            redNickname14.setEditable(true);
            redNickname15.setEditable(true);
        }
        else{
            editPlayers.setText("Edit Players (Off)");
            blueID1.setEditable(false);
            blueID2.setEditable(false);
            blueID3.setEditable(false);
            blueID4.setEditable(false);
            blueID5.setEditable(false);
            blueID6.setEditable(false);
            blueID7.setEditable(false);
            blueID8.setEditable(false);
            blueID9.setEditable(false);
            blueID10.setEditable(false);
            blueID11.setEditable(false);
            blueID12.setEditable(false);
            blueID13.setEditable(false);
            blueID14.setEditable(false);
            blueID15.setEditable(false);
            blueNickname1.setEditable(false);
            blueNickname2.setEditable(false);
            blueNickname3.setEditable(false);
            blueNickname4.setEditable(false);
            blueNickname5.setEditable(false);
            blueNickname6.setEditable(false);
            blueNickname7.setEditable(false);
            blueNickname8.setEditable(false);
            blueNickname9.setEditable(false);
            blueNickname10.setEditable(false);
            blueNickname11.setEditable(false);
            blueNickname12.setEditable(false);
            blueNickname13.setEditable(false);
            blueNickname14.setEditable(false);
            blueNickname15.setEditable(false);
            redID1.setEditable(false);
            redID2.setEditable(false);
            redID3.setEditable(false);
            redID4.setEditable(false);
            redID5.setEditable(false);
            redID6.setEditable(false);
            redID7.setEditable(false);
            redID8.setEditable(false);
            redID9.setEditable(false);
            redID10.setEditable(false);
            redID11.setEditable(false);
            redID12.setEditable(false);
            redID13.setEditable(false);
            redID14.setEditable(false);
            redID15.setEditable(false);
            redNickname1.setEditable(false);
            redNickname2.setEditable(false);
            redNickname3.setEditable(false);
            redNickname4.setEditable(false);
            redNickname5.setEditable(false);
            redNickname6.setEditable(false);
            redNickname7.setEditable(false);
            redNickname8.setEditable(false);
            redNickname9.setEditable(false);
            redNickname10.setEditable(false);
            redNickname11.setEditable(false);
            redNickname12.setEditable(false);
            redNickname13.setEditable(false);
            redNickname14.setEditable(false);
            redNickname15.setEditable(false);
            

            // SUBMIT PLAYER INFO TO DATABASE (BLUE TEAM)
            submitPlayerEntry(blueID1, blueNickname1);
            submitPlayerEntry(blueID2, blueNickname2);
            submitPlayerEntry(blueID3, blueNickname3);
            submitPlayerEntry(blueID4, blueNickname4);
            submitPlayerEntry(blueID5, blueNickname5);
            submitPlayerEntry(blueID6, blueNickname6);
            submitPlayerEntry(blueID7, blueNickname7);
            submitPlayerEntry(blueID8, blueNickname8);
            submitPlayerEntry(blueID9, blueNickname9);
            submitPlayerEntry(blueID10, blueNickname10);
            submitPlayerEntry(blueID11, blueNickname11);
            submitPlayerEntry(blueID12, blueNickname12);
            submitPlayerEntry(blueID13, blueNickname13);
            submitPlayerEntry(blueID14, blueNickname14);
            submitPlayerEntry(blueID15, blueNickname15);
        
            // SUBMIT PLAYER INFO TO DATABASE (RED TEAM)
            submitPlayerEntry(redID1, redNickname1);
            submitPlayerEntry(redID2, redNickname2);
            submitPlayerEntry(redID3, redNickname3);
            submitPlayerEntry(redID4, redNickname4);
            submitPlayerEntry(redID5, redNickname5);
            submitPlayerEntry(redID6, redNickname6);
            submitPlayerEntry(redID7, redNickname7);
            submitPlayerEntry(redID8, redNickname8);
            submitPlayerEntry(redID9, redNickname9);
            submitPlayerEntry(redID10, redNickname10);
            submitPlayerEntry(redID11, redNickname11);
            submitPlayerEntry(redID12, redNickname12);
            submitPlayerEntry(redID13, redNickname13);
            submitPlayerEntry(redID14, redNickname14);
            submitPlayerEntry(redID15, redNickname15);
        }

    }//GEN-LAST:event_editPlayersActionPerformed

    private void startGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGameActionPerformed
        java.util.Timer timer = new java.util.Timer();
        timeLeft = 6;
        TimerTask timerTask = new TimerTask() {
            public void run(){
                StartTimerLabel.setText(Integer.toString(timeLeft));
                timeLeft--;
                if(timeLeft ==-1){
                    timer.cancel();
                    PlayerActionScreen playerActionScreen = new PlayerActionScreen();
                    playerActionScreen.setVisible(true);
                    setVisible(false);
                }
                
            }
        };
        timer.scheduleAtFixedRate(timerTask, 1000, 1000);
        
        
      
    }//GEN-LAST:event_startGameActionPerformed

    public void startTimer(){
        CountdownTimer countdownTimer = new CountdownTimer(6);
        countdownTimer.start();
        while(countdownTimer.getCount()!=0){
        StartTimerLabel.setText(String.valueOf(countdownTimer.getCount()));
        }
        
        PlayerActionScreen playerActionScreen = new PlayerActionScreen();
        playerActionScreen.setVisible(true);
        setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public void showEntryScreen(){
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entry().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel StartTimerLabel;
    private javax.swing.JLabel blueCount1;
    private javax.swing.JLabel blueCount10;
    private javax.swing.JLabel blueCount11;
    private javax.swing.JLabel blueCount12;
    private javax.swing.JLabel blueCount13;
    private javax.swing.JLabel blueCount14;
    private javax.swing.JLabel blueCount15;
    private javax.swing.JLabel blueCount2;
    private javax.swing.JLabel blueCount3;
    private javax.swing.JLabel blueCount4;
    private javax.swing.JLabel blueCount5;
    private javax.swing.JLabel blueCount6;
    private javax.swing.JLabel blueCount7;
    private javax.swing.JLabel blueCount8;
    private javax.swing.JLabel blueCount9;
    private javax.swing.JTextField blueID1;
    private javax.swing.JTextField blueID10;
    private javax.swing.JTextField blueID11;
    private javax.swing.JTextField blueID12;
    private javax.swing.JTextField blueID13;
    private javax.swing.JTextField blueID14;
    private javax.swing.JTextField blueID15;
    private javax.swing.JTextField blueID2;
    private javax.swing.JTextField blueID3;
    private javax.swing.JTextField blueID4;
    private javax.swing.JTextField blueID5;
    private javax.swing.JTextField blueID6;
    private javax.swing.JTextField blueID7;
    private javax.swing.JTextField blueID8;
    private javax.swing.JTextField blueID9;
    private javax.swing.JTextField blueNickname1;
    private javax.swing.JTextField blueNickname10;
    private javax.swing.JTextField blueNickname11;
    private javax.swing.JTextField blueNickname12;
    private javax.swing.JTextField blueNickname13;
    private javax.swing.JTextField blueNickname14;
    private javax.swing.JTextField blueNickname15;
    private javax.swing.JTextField blueNickname2;
    private javax.swing.JTextField blueNickname3;
    private javax.swing.JTextField blueNickname4;
    private javax.swing.JTextField blueNickname5;
    private javax.swing.JTextField blueNickname6;
    private javax.swing.JTextField blueNickname7;
    private javax.swing.JTextField blueNickname8;
    private javax.swing.JTextField blueNickname9;
    private javax.swing.JLabel bluePlayerCodenameLabel;
    private javax.swing.JLabel bluePlayerIDLabel;
    private javax.swing.JLabel blueTeam;
    private javax.swing.JToggleButton editPlayers;
    private javax.swing.JLabel redCount1;
    private javax.swing.JLabel redCount10;
    private javax.swing.JLabel redCount11;
    private javax.swing.JLabel redCount12;
    private javax.swing.JLabel redCount13;
    private javax.swing.JLabel redCount14;
    private javax.swing.JLabel redCount15;
    private javax.swing.JLabel redCount2;
    private javax.swing.JLabel redCount3;
    private javax.swing.JLabel redCount4;
    private javax.swing.JLabel redCount5;
    private javax.swing.JLabel redCount6;
    private javax.swing.JLabel redCount7;
    private javax.swing.JLabel redCount8;
    private javax.swing.JLabel redCount9;
    private javax.swing.JTextField redID1;
    private javax.swing.JTextField redID10;
    private javax.swing.JTextField redID11;
    private javax.swing.JTextField redID12;
    private javax.swing.JTextField redID13;
    private javax.swing.JTextField redID14;
    private javax.swing.JTextField redID15;
    private javax.swing.JTextField redID2;
    private javax.swing.JTextField redID3;
    private javax.swing.JTextField redID4;
    private javax.swing.JTextField redID5;
    private javax.swing.JTextField redID6;
    private javax.swing.JTextField redID7;
    private javax.swing.JTextField redID8;
    private javax.swing.JTextField redID9;
    private javax.swing.JTextField redNickname1;
    private javax.swing.JTextField redNickname10;
    private javax.swing.JTextField redNickname11;
    private javax.swing.JTextField redNickname12;
    private javax.swing.JTextField redNickname13;
    private javax.swing.JTextField redNickname14;
    private javax.swing.JTextField redNickname15;
    private javax.swing.JTextField redNickname2;
    private javax.swing.JTextField redNickname3;
    private javax.swing.JTextField redNickname4;
    private javax.swing.JTextField redNickname5;
    private javax.swing.JTextField redNickname6;
    private javax.swing.JTextField redNickname7;
    private javax.swing.JTextField redNickname8;
    private javax.swing.JTextField redNickname9;
    private javax.swing.JLabel redPlayerCodenameLabel;
    private javax.swing.JLabel redPlayerIDLabel;
    private javax.swing.JLabel redTeam;
    private javax.swing.JButton startGame;
    // End of variables declaration//GEN-END:variables
}
